export default function Head() {
    return (
      <>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* 🔥 This line forces the favicon to load */}
        <link rel="icon" href="/kristens1_logo.ico" />
      </>
    );
  }
  